export const data = {
  id: 319425558,
  name: 'ТестИван',
  surname: 'фамилия',
  patronymic: 'отчествович',
  display_name: 'ТестИван отчествович фамилия',
  phone: '+37377891434',
  email: '',
  card: '',
  birth_date: '',
  comment: '',
  discount: 0,
  visits: 2,
  sex_id: 1,
  sex: 'Мужской',
  sms_check: 0,
  sms_bot: 0,
  sms_not: 0,
  spent: 0,
  paid: 0,
  balance: 0,
  importance_id: 0,
  importance: 'Без класса важности',
  categories: [
    {
      id: 9310908,
      salon_id: 362779,
      company_id: 362779,
      title: 'Запрос наличных',
      color: '#ebff00',
      font_color: '#000000',
      icon: 'tag',
      entity: 1,
      entity_slug: 'client',
      deleted: 0,
      is_deleted: false,
      not_editable: 0,
      is_editable: true
    },
    {
      id: 9313774,
      salon_id: 362779,
      company_id: 362779,
      title: 'Лоялен к наличным',
      color: '#77ff9d',
      font_color: '#000000',
      icon: 'tag',
      entity: 1,
      entity_slug: 'client',
      deleted: 0,
      is_deleted: false,
      not_editable: 0,
      is_editable: true
    }
  ],
  last_change_date: '2025-12-16T14:42:13+0400',
  custom_fields: { Docs: '24.07.2025' }
};
